

pool:
  vmImage: 'ubuntu-latest'

steps: 

- task: CmdLine@2
  inputs:
    script: 'dotnet build ./site/site.csproj'
- task: SnykSecurityScan@0
  inputs:
    serviceConnectionEndpoint: 'Snyk - sjb github'
    testType: 'app'
    monitorOnBuild: true
    failOnIssues: true
    projectName: 'Staggerlee011/dotnet' 
    organization: 'e6178940-aa14-445d-8073-4957c814432b'

- task: CmdLine@2
  inputs:
    script: |
      docker build -t mycontainer ./site
      docker images
      docker images | grep mycontainer

- task: SnykSecurityScan@0
  inputs:
    serviceConnectionEndpoint: 'Snyk - sjb github'
    testType: 'container'
    dockerImageName: 'mycontainer'
    dockerfilePath: 'site/dockerfile'
    monitorOnBuild: true
    failOnIssues: false
    projectName: 'Staggerlee011/dotnet' 
    organization: 'e6178940-aa14-445d-8073-4957c814432b'

