
pool:
 vmImage: 'ubuntu-latest'

steps:

- script: dotnet build ./site/site.csproj
  displayName: 'Build cs project'
- task: SnykSecurityScan@0
  inputs:
   serviceConnectionEndpoint: 'Snyk - sjb github'
   projectName: 'Staggerlee011/dotnet '
   organization: 'e6178940-aa14-445d-8073-4957c814432b'
   testType: 'app'
   targetFile: 'site/site.sln'
   monitorOnBuild: true
   failOnIssues: true


