FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY *.csproj ./
RUN dotnet restore

# copy everything else and build app
COPY ./ ./
WORKDIR /app
RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
WORKDIR /app
COPY --from=build /app/out ./

ENTRYPOINT ["dotnet", "/app/site.dll"]

# ASP.NET Core: Kestrel should listen on all IPs
# ENV ASPNETCORE_URLS="http://0.0.0.0:5000"

# ASP.NET Core: make sure views use the production versions
ENV ASPNETCORE_ENVIRONMENT="Production"
