FROM mcr.microsoft.com/dotnet/core/aspnet:3.0

RUN mkdir /app
COPY ./bin/Release/netcoreapp3.0/publish /app
WORKDIR /app

ENTRYPOINT ["dotnet", "/app/site.dll"]

# ASP.NET Core: Kestrel should listen on all IPs
ENV ASPNETCORE_URLS="http://0.0.0.0:5000"

# ASP.NET Core: make sure views use the production versions
ENV ASPNETCORE_ENVIRONMENT="Production"
